name = "dvoracekdev"
version = "2.0.0"
description = "The source code of my personal website powered by Gleam."
links = [{ title = "Deployment", href="https://dvoracek.dev" }]

repository = { type = "github", user = "portrik", repo = "website"}
licenses = ["MIT"]

gleam = ">= 1.13.0"

[dependencies]
gleam_stdlib = "0.65.0"
lustre = "5.4.0"
lustre_ssg = "0.11.0"

[dev-dependencies]
gleeunit = "1.9.0"
